// Code generated by Nexus Automation, DO NOT EDIT.

package consult

import (
	"context"
	"net/http"

	"github.com/nexusmed/nexusmed-go/client"
)

type Client struct {
	Client *client.Client
}

func NewClient(cli *http.Client, options ...client.HTTPRequestOption) *Client {
	return &Client{Client: client.NewClient(cli, "https://api.nexusmed.io/consult", options...)}
}

type Query struct {
	GetQuestionnaire        *Questionnaire        "json:\"getQuestionnaire\" graphql:\"getQuestionnaire\""
	GetQuestionnaires       *Questionnaires       "json:\"getQuestionnaires\" graphql:\"getQuestionnaires\""
	GetQuestionnaireAnswers *QuestionnaireAnswers "json:\"getQuestionnaireAnswers\" graphql:\"getQuestionnaireAnswers\""
	GetConsultation         Consultation          "json:\"getConsultation\" graphql:\"getConsultation\""
}
type Mutation struct {
	CreateQuestionnaire *Questionnaire        "json:\"createQuestionnaire\" graphql:\"createQuestionnaire\""
	AnswerQuestionnaire *QuestionnaireAnswers "json:\"answerQuestionnaire\" graphql:\"answerQuestionnaire\""
	CreateConsultation  Consultation          "json:\"createConsultation\" graphql:\"createConsultation\""
}
type QuestionParts struct {
	Index   int            "json:\"index\" graphql:\"index\""
	Type    QuestionType   "json:\"type\" graphql:\"type\""
	Text    string         "json:\"text\" graphql:\"text\""
	Answers []*AnswerParts "json:\"answers\" graphql:\"answers\""
}
type AnswerParts struct {
	Index  int    "json:\"index\" graphql:\"index\""
	Value  string "json:\"value\" graphql:\"value\""
	Reject bool   "json:\"reject\" graphql:\"reject\""
}
type GetQuestionnaire struct {
	GetQuestionnaire *struct {
		ID        string           "json:\"id\" graphql:\"id\""
		Title     *string          "json:\"title\" graphql:\"title\""
		Questions []*QuestionParts "json:\"questions\" graphql:\"questions\""
	} "json:\"getQuestionnaire\" graphql:\"getQuestionnaire\""
}
type CreateConsultation struct {
	CreateConsultation *struct {
		Typename      *string "json:\"__typename\" graphql:\"__typename\""
		IConsultation struct {
			ID     string             "json:\"id\" graphql:\"id\""
			Status ConsultationStatus "json:\"status\" graphql:\"status\""
		} "graphql:\"... on IConsultation\""
	} "json:\"createConsultation\" graphql:\"createConsultation\""
}
type CreateQuestionnaire struct {
	CreateQuestionnaire *struct {
		ID        string           "json:\"id\" graphql:\"id\""
		Title     *string          "json:\"title\" graphql:\"title\""
		Questions []*QuestionParts "json:\"questions\" graphql:\"questions\""
	} "json:\"createQuestionnaire\" graphql:\"createQuestionnaire\""
}
type AnswerQuestionnaire struct {
	AnswerQuestionnaire *struct {
		ID      string "json:\"id\" graphql:\"id\""
		Answers []*struct {
			Question QuestionParts "json:\"question\" graphql:\"question\""
			Value    []string      "json:\"value\" graphql:\"value\""
		} "json:\"answers\" graphql:\"answers\""
	} "json:\"answerQuestionnaire\" graphql:\"answerQuestionnaire\""
}

const GetQuestionnaireDocument = `query GetQuestionnaire ($id: ID!) {
	getQuestionnaire(id: $id) {
		id
		title
		questions {
			... QuestionParts
		}
	}
}
fragment QuestionParts on Question {
	index
	type
	text
	answers {
		... AnswerParts
	}
}
fragment AnswerParts on Answer {
	index
	value
	reject
}
`

func (c *Client) GetQuestionnaire(ctx context.Context, id string, httpRequestOptions ...client.HTTPRequestOption) (*GetQuestionnaire, error) {
	vars := map[string]interface{}{
		"id": id,
	}

	var res GetQuestionnaire
	if err := c.Client.Post(ctx, "GetQuestionnaire", GetQuestionnaireDocument, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const CreateConsultationDocument = `mutation CreateConsultation ($input: CreateConsultationInput!) {
	createConsultation(input: $input) {
		__typename
		... on IConsultation {
			id
			status
		}
	}
}
`

func (c *Client) CreateConsultation(ctx context.Context, input CreateConsultationInput, httpRequestOptions ...client.HTTPRequestOption) (*CreateConsultation, error) {
	vars := map[string]interface{}{
		"input": input,
	}

	var res CreateConsultation
	if err := c.Client.Post(ctx, "CreateConsultation", CreateConsultationDocument, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const CreateQuestionnaireDocument = `mutation CreateQuestionnaire ($input: CreateQuestionnaireInput!) {
	createQuestionnaire(input: $input) {
		id
		title
		questions {
			... QuestionParts
		}
	}
}
fragment QuestionParts on Question {
	index
	type
	text
	answers {
		... AnswerParts
	}
}
fragment AnswerParts on Answer {
	index
	value
	reject
}
`

func (c *Client) CreateQuestionnaire(ctx context.Context, input CreateQuestionnaireInput, httpRequestOptions ...client.HTTPRequestOption) (*CreateQuestionnaire, error) {
	vars := map[string]interface{}{
		"input": input,
	}

	var res CreateQuestionnaire
	if err := c.Client.Post(ctx, "CreateQuestionnaire", CreateQuestionnaireDocument, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const AnswerQuestionnaireDocument = `mutation AnswerQuestionnaire ($input: AnswerQuestionnaireInput!) {
	answerQuestionnaire(input: $input) {
		id
		answers {
			question {
				... QuestionParts
			}
			value
		}
	}
}
fragment QuestionParts on Question {
	index
	type
	text
	answers {
		... AnswerParts
	}
}
fragment AnswerParts on Answer {
	index
	value
	reject
}
`

func (c *Client) AnswerQuestionnaire(ctx context.Context, input AnswerQuestionnaireInput, httpRequestOptions ...client.HTTPRequestOption) (*AnswerQuestionnaire, error) {
	vars := map[string]interface{}{
		"input": input,
	}

	var res AnswerQuestionnaire
	if err := c.Client.Post(ctx, "AnswerQuestionnaire", AnswerQuestionnaireDocument, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}
